version: "3.3"  # optional since v1.27.0
services:

  entity_relation_extractor:
    container_name: entity_relation_extractor
    build: .
    ports:
      - "8000:8000"
    networks:
      - net
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - type: bind
        source: ./RECON_data
        target: /RECON_data
        read_only: true
        
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    mem_limit: 4g
    networks:
      - net


networks:
  net:

